### ISSUE TITLE
想知道屏蔽独显的主要几个地方在哪呢

### ISSUE THREAD

**Issue by UG3800** [FrostMiKu/msi-z370-i5-9500-hackintosh#1]
屏蔽独显主要是boot-args的-wegnoegpu
DeviceProperties那里要注入好核显驱动，想知道还有其他地方吗

我的配置是（MSI B360+8400+GTX1060）

**Comment by FrostMiKu** [comment]
你好👋，在bios里把启动时的显卡设置成IGD
嗯，应该没有其他的了
