### ISSUE TITLE
请问MSI z370 oc gaming主板能用这个EFI吗？

### ISSUE THREAD

**Issue by ShawLocke** [FrostMiKu/msi-z370-i5-9500-hackintosh#2]
你好，请问MSI z370 oc gaming主板能用这个EFI吗？谢谢

**Comment by FrostMiKu** [comment]
应该可以，你可以尝试一下。
可能会需要对配置文件做少量修改

**Comment by ShawLocke** [comment]
@FrostMiKu 感谢回复，我今天中午详细对比了msi z370 a pro和z370 oc gaming 2块主板，几乎一样，前者多了一个dvi接口。我晚上试试。请问这个EFI可以装10.15.7不？

**Comment by FrostMiKu** [comment]
@ShawLocke 时间太久了，我不记得有没有支持10.15.7了。似乎是从10.15.4直接更新了 big sur
但我认为你使用较新的OpenCore应该可以在10.15.7上良好work （请不要使用我 commit history 里的版本

**Comment by ShawLocke** [comment]
@FrostMiKu 昨晚用你的EFI安装了10.15.7，安装很顺利。除了以太网不行，其他都可以，谢谢。

1. 请问网络里没有以太网这一项，你知道要改哪里的设置吗？
2. 我用的是8600k，**没有用**独显，机型是不是保持你EFI中的macmini8,1不变？

**Comment by FrostMiKu** [comment]
@ShawLocke 很高兴听到EFI能够正常工作的消息，我将会更新到ReadMe里。
 1. 网络里没有以太网选项可能是因为`/EFI/OC/Kexts/`中的 IntelMausi.kext 驱动没有正确工作
    1.1 尝试更新该驱动程序
    1.2 不行的话就替换其他的Intel网卡驱动程序
 2. 机型不需要修改
 3. 推荐你使用`hackintool`工具内建USB端口

**Comment by ShawLocke** [comment]
@FrostMiKu 我确认过每个接口都能正常工作，可能是由于这两块主板除了一个vgi以外完全一样。请问还需要用`hackintool`内建USB端口吗？请问目前EFI用的OC版本是多少？怎么看？

**Comment by FrostMiKu** [comment]
@ShawLocke 内建是为了防止系统睡眠时被意外唤醒的，如果没有睡眠需求，其实不内建也行。`hackintool`可以查看 OC&驱动 版本与可用更新。

**Comment by ShawLocke** [comment]
@FrostMiKu 谢谢回复。昨晚特定测试了睡眠，正常，然后让机器睡眠了一晚上，今天早上启动也正常，网络等都正常。如果后续发现睡眠时被意外唤醒，我到时候再去内建。请问内建教程建议看哪个？

**Comment by FrostMiKu** [comment]
@ShawLocke 推荐[黑果小兵的教程](https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html) 
另外，如果你解决了网卡问题，希望能提一个 PR

**Comment by ShawLocke** [comment]
@FrostMiKu 嗯嗯，如果我解决了，会的哈

**Comment by ShawLocke** [comment]
@FrostMiKu 我昨晚重装时，发现EFI用不了啦，我拍了个视频，有点大，上传不上来，请问方便给个联系方式不？想请教一下。

**Comment by FrostMiKu** [comment]
@ShawLocke 还有这种事？建议你先尝试使用黑果小兵的通用安装镜像进行安装，待安装完成后再将EFI替换进去。
进一步联系email：i#frostmiku.com

**Comment by ShawLocke** [comment]
@FrostMiKu 
你的BIOS版本是？
BIOS设置有什么特别的地方吗？我昨天将BIOS恢复到默认值后，无法开机，然后查了一下发现必须XHCI Hand-off enable。然后我想说重装试试看，结果老是卡在这个弹窗，以前装黑果重来没遇到过：

![image](https://user-images.githubusercontent.com/41377090/129430778-1116bf48-7407-4073-9eb6-ac6c008b5bf0.png)

![image](https://user-images.githubusercontent.com/41377090/129430809-21b39e0c-a342-4ca0-b142-4a15b41a15a2.png)


我用的是这个镜像：
![image](https://user-images.githubusercontent.com/41377090/129430698-b075fcf0-07d9-4d58-a538-bdd50424f51f.png)

你的email地址不对？
![image](https://user-images.githubusercontent.com/41377090/129430656-9ba6c1e3-7b23-469d-aa94-50330f7c19ab.png)

**Comment by FrostMiKu** [comment]
@ShawLocke 既然昨天能用那就应该不是bios版本的问题，设置参考下图，不存在的设置项忽略

![image](https://user-images.githubusercontent.com/8232546/129431618-65a676cc-9ae3-4851-aa64-e3830e63c11d.jpeg)

记得把显存调到 64M

邮箱的#改成@啊 🤔

**Comment by ShawLocke** [comment]
@FrostMiKu 
帮忙看看？

https://user-images.githubusercontent.com/41377090/129432697-4932495f-ed1b-4112-b2ca-a7dfc2b09d8a.mp4

**Comment by FrostMiKu** [comment]
@ShawLocke 没能看出什么问题，建议先按我说的方法试试

**Comment by ShawLocke** [comment]
@FrostMiKu BIOS是按照你说的设置的，还是不行。

我记得上次装成功，是根据这个设置：
![image](https://user-images.githubusercontent.com/41377090/129433644-6f5b9c02-b308-4c95-a981-a60e0dfdfe91.png)
来源: https://github.com/luffythink/Hackintosh-EFI

**Comment by FrostMiKu** [comment]
> @ShawLocke 还有这种事？建议你先尝试使用黑果小兵的通用安装镜像进行安装，待安装完成后再将EFI替换进去。
> 进一步联系email：i#frostmiku.com

@ShawLocke 我是指这个，你是先替换EFI还是先安装的

**Comment by ShawLocke** [comment]
@FrostMiKu 明白了。我是先拿你的EFI替换了黑果小兵的。我试试先安装，再替换试试

**Comment by ShawLocke** [comment]
@FrostMiKu 先用黑果小兵的通用安装镜像进行安装，成功。然后替换你的EFI，成功。谢谢了。你建议的这个流程比较稳妥。
